services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    expose:
      - "3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - prv-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "admin", "-padmin", "-P", "3306"]
      interval: 8s
      timeout: 8s
      retries: 5
      start_period: 20s

  backend: 
    image: {USERNAME}/${BACKEND}:${GIT_COMMIT}
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: crud_app
      JWT_SECRET: devopsShackSuperSecretKey
    expose:
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - prv-network
      - pub-network

  frontend:
    image: {USERNAME}/${FRONTEND}:${GIT_COMMIT}
    container_name: frontend
    environment:
      REACT_APP_API: http://backend:5000
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - pub-network
    # for SSL certificate mounting into the container from host
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro

volumes:
  mysql-data:

networks:
  prv-network:
    driver: bridge
  pub-network:
    driver: bridge

